#!/bin/bash
if [[ -z $1 ]]; then
  echo -e "\e[91mError: No channel specified.\e[0m"
  exit 1
fi

playlist="$HOME/.tv_playlist"

if [[ -f "$playlist" ]]; then
  search_results="$(grep  --color=always -i "$1" $playlist)"
  num_results=$(echo -e "$search_results" | wc -l)

  if [[ -z "$search_results" ]]; then
    echo -e "\e[91mChannel not found\e[0m"
    exit 1
  elif [[ $num_results > 1 ]]; then
    echo -e "$search_results"
    echo -e "\n\e[91mMultitple results found. Refine search.\e[0m"
    exit 1
  else
    sh -c "mpv -really-quiet -cache 2048 $search_results"
  fi
else
  echo -e "\e[91mPlaylist not found\e[0m"
  exit 1
fi
